---
- name: Instala o puppetserver nos RHEL 7
  yum:
    name: puppetserver
    state: present
  when: ansible_os_family == "RedHat"
  notify:
  - reinicia o server

- name: Instala o puppetserver nos Debian
  apt:
    name: puppetserver
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  notify:
  - reinicia o server
